export default {
  bikes: [{
    manufacturer: 'Ducati',
    model: 'Monster 821 Stealth',
    power: '109 hp (80 kW)',
    description: 'The Monster 821 pays homage to the legacy of the Monster 900, which over 25 years ago revolutionized the motorcycle world. Agile and featuring sporty performance, it was designed for maximum riding enjoyment, at all times and in all conditions.  The Monster 821 range has been rejuvenated with a new stealth version: matte black livery, updated graphics and front fairing give a unique character to the naked Ducati par excellence.',
    color: 'Stealth Black',
    displacement: '821 cc',
    year: '2020',
    image: 'monster821stealth.png',
    id: 'monster',
  },
  {
    manufacturer: 'BMW',
    model: 'F 750 GS',
    power: '77 hp (at 7,500 rpm)',
    description: "The BMW F 750 GS is your ticket to adventure. With this balanced Enduro all-rounder, you can master all paths and expand your horizons. The F 750 GS gives you more power, more comfort, more spirit of GS. Feel the strong-charactered engine and enjoy the ease of handling of the F 750 GS. While you're off discovering the world, you have the bike safely under control with the Automatic Stability Control (ASC) and ABS. With the additional option Connectivity, the 6.5 inch TFT-display boasts many features including navigation and smartphone connectivity.",
    color: 'Austin Yellow Metallic',
    displacement: '853 cc',
    year: '2020',
    image: 'f750gs.png',
    id: 'f750',
  },
  {
    manufacturer: 'Indian',
    model: 'Scout Bobber',
    power: '100 hp',
    description: 'Stripped down and blacked out with an aggressive stance and raw power, the Scout Bobber is a modern take on the iconic bobber style.',
    color: 'Black',
    displacement: '1,133 cc',
    year: '2020',
    image: 'scoutBobber.jpg',
    id: 'scoutBobber',
  },
  {
    manufacturer: 'Ducati',
    model: 'Panigale V4',
    power: '157.5 kW (214 hp)',
    description: 'The 2020 version of the Panigale V4 boosts performance even further and takes track riding to the next level for amateurs and pros alike. ',
    color: 'Ducati Red',
    displacement: '1,103 cc',
    year: '2020',
    image: 'panigaleV4.png',
    id: 'panigale',
  },
  {
    manufacturer: 'Yamaha',
    model: 'R3',
    power: '31 kW (42 hp)',
    description: 'My first motorcycle that I rode for my entire first season. It was the perfect beginner bike, with just enough power to have a lot of fun without being too wrapped up in fear. lThe Yamaha YZF-R3, commonly R3, is a 321 cc inline-twin sport bike made by Yamaha since 2015. The R3 and the R25 are the first Yamaha twins with an offset cylinder design. The YZF-R3 was updated for 2019.',
    color: 'Blue and white',
    displacement: '321 cc',
    year: '2015',
    image: 'r3.jpg',
    id: 'r3',
  },
  {
    manufacturer: 'Kawasaki',
    model: 'Z650',
    power: '69hp',
    description: 'The bike that very quickly became the dream as soon as I wanted to upgrade, and my now current baby. Quite a lot more power and zip and a gorgeous aesthetic. On the way to being more customized soon. Middleweight brother to the popular Z400 and Z900, the 2020 Kawasaki Z650 brings a punch of power with its 649cc twin-cylinder engine. Boasting redesigned elements in the sharper Sugomi styling, new TFT dash, new Dunlop Sportmax Roadsport 2 rubber, and thicker padded passenger seat, this naked bike continues to flaunt its athletic daily-grind versatility while giving some attention to creature comforts.',
    color: 'Spark Black',
    displacement: '649 cc',
    year: '2020',
    image: 'z650.jpg',
    id: 'z650',
  }],
};
